<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/*
Template Name: Loan Calculator
*/


remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'custom_genesis_standard_loop' );

remove_action( 'genesis_after_content', 'genesis_get_sidebar' );


function custom_genesis_standard_loop() {

	//* Use old loop hook structure if not supporting HTML5
	if ( ! genesis_html5() ) {
		genesis_legacy_loop();
		return;
	}

	if ( have_posts() ) :

		do_action( 'genesis_before_while' );
		while ( have_posts() ) : the_post();

			do_action( 'genesis_before_entry' );

			printf( '<section class="subpage-container"><div class="wrap">' );
			?>
			
            <link type='text/css' rel='StyleSheet' href='<?php echo get_stylesheet_directory_uri() ?>/css/KJE.css' />
			<link type='text/css' rel='StyleSheet' href='<?php echo get_stylesheet_directory_uri() ?>/css/KJESiteSpecific.css' />
            
            <div class=KJEWrapper>
              <div class=KJEWidthConstraint>
                <center>
                  <img src='<?php echo get_stylesheet_directory_uri() ?>/images/calclogo.png' alt="msculogo">
                </center>
                <br>
                <h1 style="font-size:18px;">Amortizing Loan Calculator</h1>
                
                <!--CALC_DESC--> 
                
                Enter your desired payment - and let us calculate your loan amount. Or, enter in the loan amount and we will calculate your monthly payment. You can then examine your principal balances by payment, total of all payments made, and total interest paid. Press the report button to see a monthly payment schedule. 
                
                <!--CALC_DESC_END-->
                <noscript>
                <div align=center>
                  <div align=center id=KJENoJavaScript class=KJENoJavaScript>Javascript is required for this calculator.  If you are using Internet Explorer, you may need to select to 'Allow Blocked Content' to view this calculator.
                    <p><strong>For more information about these these financial calculators please visit: <A href=http://www.dinkytown.net target=_blank>Financial Calculators</a> from KJE Computer Solutions, LLC</strong></p>
                  </div>
                </div>
                </noscript>
                <div id="KJEAllContent"></div>
                <!--
                          Financial Calculators, ©1998-2014 KJE Computer Solutions, LLC.
                          For more information please see:
                          <A HREF="http://www.dinkytown.net">http://www.dinkytown.net</A>
                         --> 
                
                <!--[if lt IE 9]>
                        <script language="JavaScript" SRC="excanvas.js"></script>
                        <![endif]--> 
                <script language="JavaScript" type="text/javascript" SRC="<?php echo get_stylesheet_directory_uri() ?>/js/KJE.js"></script> 
                <script language="JavaScript" type="text/javascript" SRC="<?php echo get_stylesheet_directory_uri() ?>/js/KJESiteSpecific.js"></script> 
                <script language="JavaScript" type="text/javascript" SRC="<?php echo get_stylesheet_directory_uri() ?>/js/SimpleLoan.js"></script> 
                <script language="JavaScript" type="text/javascript" SRC="<?php echo get_stylesheet_directory_uri() ?>/js/SimpleLoanParams.js"></script> 
                <br>
                <hr size=1>
                <div align=center>
                  <p><span class='KJEBold'>MemberSource Credit Union</span><br>
                    10100 Richmond Avenue<br>
                    Houston, Tx</p>
                  <p class=KJEFooter>Information and interactive calculators are made available to you as self-help tools for your independent use and are not intended to provide investment advice. We cannot and do not guarantee their applicability or accuracy in regards to your individual circumstances. All examples are hypothetical and are for illustrative purposes.  We encourage you to seek personalized advice from qualified professionals regarding all personal finance issues. </p>
                </div>
              </div>
            </div>
            
            
		<?php
			printf( '</div></section>' );

			do_action( 'genesis_after_entry' );

		endwhile; //* end of one post
		do_action( 'genesis_after_endwhile' );
	
		printf( '<div class="footer-breadcrumb">' );	
				breadcrumb_hook();
			printf( '</div>' );

		dynamic_sidebar( 'footer-banner-widget' ); 

	else : //* if no posts exist
		do_action( 'genesis_loop_else' );
	endif; //* end loop

}
//* Remove edit link
add_filter( 'genesis_edit_post_link' , '__return_false' );
genesis();


