<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

/*
Template Name: Calculator template
*/


remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'custom_genesis_standard_loop' );

remove_action( 'genesis_after_content', 'genesis_get_sidebar' );


function custom_genesis_standard_loop() {

	//* Use old loop hook structure if not supporting HTML5
	if ( ! genesis_html5() ) {
		genesis_legacy_loop();
		return;
	}

	if ( have_posts() ) :

		do_action( 'genesis_before_while' );
		while ( have_posts() ) : the_post();

			do_action( 'genesis_before_entry' );

			printf( '<section class="subpage-container"><div class="wrap">' );
			?>

<div class="custom-calc">
  <table border="0" align="center">
    <tbody>
      <tr>
        <td></td>
        <td><span face="Arial,Helvetica">Calculate <a href="/financial-calculators/loan-payments/">Loan Payments</a></span></td>
      </tr>
      <tr>
        <td></td>
        <td><span face="Arial,Helvetica">Calculate <a href="/financial-calculators/rate-vs-rebate/">Rate vs. Rebate</a></span></td>
      </tr>
      <tr>
        <td></td>
        <td><span face="Arial,Helvetica">Calculate <a href="/financial-calculators/amortization/">Amortization</a></span></td>
      </tr>
      <tr>
        <td></td>
        <td><span face="Arial,Helvetica">Calculate <a href="/financial-calculators/future-savings/">Future Savings</a></span></td>
      </tr>
      <tr>
        <td></td>
        <td><span face="Arial,Helvetica">Calculate <a href="/financial-calculators/kids/">Kids Savings</a></span></td>
      </tr>
    </tbody>
  </table>
  <br />
  <CENTER>
    <FORM NAME="frmCalc" action="https://www.membersourcecu.org/financial-calculators/kids/?TYPE=Kids" method="get" onsubmit="javascript:return ValidateForm(this)">
      <INPUT TYPE=Hidden NAME=TYPE VALUE=Kids aria-label="kid-cal">
      <TABLE borderColor=slategray cellSpacing=0 borderColorDark=black cellPadding=0 
			width=350px borderColorLight=slategray border=7>
        <TBODY>
          <TR>
            <TD><TABLE cellSpacing=0 cellPadding=0 width="100%" bgColor=#dfeaf9 border=0>
                <TBODY>
                  <TR>
                    <TD align=middle colSpan=2>
                      <TABLE borderColor=slategray cellSpacing=0 borderColorDark=black cellPadding=0 
			width="75%" borderColorLight=slategray border=7>
                        <TBODY>
                          <TR>
                            <TD align=middle bgColor=#385a88>
                              <!-- Begin Edititable portion Top of Calculator Here--> 
                              <br /><span style="color: yellow;">Enter your Values...and Press Enter</span> 
                              <!-- End Edititable portion Top of Calculator--> 
                              <BR>
                              <BR>
                              </span></TD>
                          </TR>
                        </TBODY>
                      </TABLE>
                      </TD>
                  </TR>
                  <TR>
                    <TD align=middle><span face=ARIAL color=black size=2><NOBR><strong>Dollars saved <br>
                      each month<BR>
                      <span 
			face=ARIAL size=2>
					  <label for="calk" style="line-height:0; color:#fff; span-size: 0px; display:block;">calculator</label>
                      <INPUT TYPE=TEXT size=9 value="" NAME=AMOUNT aria-label="kid-amount" id="calk">
                      $</span></strong></NOBR></span></TD>
                    <TD align=middle><INPUT TYPE=Hidden value="0" NAME=DOWNPAYMENT aria-label="kid-payment">
                      <INPUT TYPE=Hidden value="0" NAME=INTEREST aria-label="kid-rate">
                      <span face=ARIAL size=2 color=black><NOBR><strong>Number of<br>
                      Months<BR>
                      <span face=ARIAL size=2>
						  <label for="calkt" style="line-height:0; color:#fff; span-size: 0px; display:block;">calculator</label>
                      <INPUT TYPE=TEXT value="" size=4 NAME=TERM aria-label="kid-term" id="calkt">
                      </span></strong></NOBR></TD>
                  </TR>
                  <TR>
                    <TD colSpan=2><HR></TD>
                  </TR>
                  <TR>
                    <TD align=middle colSpan=2><INPUT type=submit value=Enter name=ENTER>
                      <br /><br />
                      </TD>
                  </TR>
                </TBODY>
              </TABLE>
              
              <!-- end of calculator table--></TD>
          </TR>
        </TBODY>
      </TABLE>
    </FORM>
  </CENTER>
  <br />
  
  <?php 
   $result = ($_GET["ENTER"]);
   if($result == 'Enter') { ?>
  
  <center>
    <h3>Wow, after saving <?php echo $_GET['AMOUNT']; ?> a month for <?php echo $_GET['TERM']; ?> months you'll have<br>
      <?php $totalvalue = $_GET['AMOUNT']*$_GET['TERM']; echo '$'.$totalvalue; ?>
      .00 dollars!
      <p></p>
      <ul>
        <table border="1" style="width: 550px;">
          <tbody>
            <tr>
              <td align="middle" bgcolor="#ff00ff" colspan="5"><span size="4">Kid's Wizard Calculation Table</span></td>
            </tr>
            <tr>
              <td valign="center" align="middle" bgcolor="#00ccff"><span size="3"><strong>Dollars<br>
                you could<br>
                save</strong></span></td>
              <td valign="center" align="middle" bgcolor="#00ff99"><span size="3"><strong>Multiplied by</strong></span></td>
              <td valign="center" align="middle" bgcolor="#ffff66"><span size="3"><strong>The number<br>
                of months</strong></span></td>
              <td valign="center" align="middle" bgcolor="#ffcccc"><span size="3"><strong>Equals</strong></span></td>
              <td valign="center" align="middle" bgcolor="#ff9966"><span size="3"><strong>Total amount<br>
                you could<br>
                save</strong></span></td>
            </tr>
            <tr>
              <td valign="center" align="middle" bgcolor="#ffcc00"><span color="#ff0000" size="5"><?php echo $_GET['AMOUNT']; ?></span></td>
              <td valign="center" align="middle" bgcolor="#ff99ff"><span color="#ff0000" size="5"><strong>X</strong></span></td>
              <td valign="center" align="middle" bgcolor="#ccff00"><span color="#ff0000" size="5"><?php echo $_GET['TERM']; ?></span></td>
              <td valign="center" align="middle" bgcolor="#0099ff"><span color="#ff0000" size="5"><strong>=</strong></span></td>
              <td valign="center" align="middle" bgcolor="#ffff99"><span color="#ff0000" size="5">
                <?php $totalvalue = $_GET['AMOUNT']*$_GET['TERM']; echo '$'.$totalvalue; ?>
                .00</span></td>
            </tr>
          </tbody>
        </table>
      </ul>
    </h3>
  </center>
  
  <?php } ?>
  
  <CENTER>
    <HR width=150>
    <TABLE borderColor=slategray cellSpacing=0 borderColorDark=black cellPadding=0 
			borderColorLight=slategray border=4>
      <TBODY>
        <TR>
          <TD><TABLE cellSpacing="0" cellPadding="2" bgColor="#dfeaf9" style="width:450px;">
              <TBODY>
                <TR>
                  <TD><span face="Arial, Times New Roman"><span size=2><span color=blue><strong>Help 
                    Information</strong><BR>
                    Use this calculator to determine the value of your savings 
                    given...</span></span></span></TD>
                </TR>
                <TR>
                  <TD><span face="Arial, Times New Roman"><span size=2>
                    <strong>[Dollars saved each month]</strong> - The standard monthly 
                    contribution</span></span></TD>
                </TR>
                <TR>
                  <TD><span face="Arial, Times New Roman"><span size=2>
                    <strong>[Number of Months]</strong> - The number of months of 
                    contribution</span></span></TD>
                </TR>
                <TR>
                  <TD>&nbsp;</TD>
                </TR>
              </TBODY>
            </TABLE></TD>
        </TR>
      </TBODY>
    </TABLE>
    <HR width=150>
  </CENTER>
</div>
<?php
			printf( '</div></section>' );

			do_action( 'genesis_after_entry' );

		endwhile; //* end of one post
		do_action( 'genesis_after_endwhile' );
	
		printf( '<div class="footer-breadcrumb">' );	
				breadcrumb_hook();
			printf( '</div>' );

		dynamic_sidebar( 'footer-banner-widget' ); 

	else : //* if no posts exist
		do_action( 'genesis_loop_else' );
	endif; //* end loop

}
//* Remove edit link
add_filter( 'genesis_edit_post_link' , '__return_false' );
genesis();
